using System;
using System.Windows.Forms;
using System.Drawing;

namespace NPNDAutoVNC
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {

            this.components = new System.ComponentModel.Container();

            //this.components = new Container();
            this.gridlist = new DataGridView();
            this.IP = new DataGridViewTextBoxColumn();
            this.Status = new DataGridViewTextBoxColumn();
            this.Action = new DataGridViewTextBoxColumn();
            this.btGetPoint = new Button();
            this.btSave = new Button();
            this.labpoint = new Label();
            this.txtslapp = new TextBox();
            this.label1 = new Label();
            this.txtwidth = new TextBox();
            this.label2 = new Label();
            this.btStart = new Button();
            this.timerphut = new System.Windows.Forms.Timer(this.components);
            this.txt1to24 = new TextBox();
            this.timerGiay = new System.Windows.Forms.Timer(this.components);
            this.timer5p = new System.Windows.Forms.Timer(this.components);
            this.timer10p = new System.Windows.Forms.Timer(this.components);
            this.btStop = new Button();
            this.label4 = new Label();
            this.label5 = new Label();
            this.checkBoxStartAndClose = new CheckBox();
            this.numTick = new NumericUpDown();
            this.txthight = new TextBox();
            this.label3 = new Label();
            this.label6 = new Label();
            this.checkBoxIsStartApp = new CheckBox();
            this.timerCount = new System.Windows.Forms.Timer(this.components);
            this.label7 = new Label();
            this.txtmouseX = new NumericUpDown();
            this.txtmouseY = new NumericUpDown();
            this.btsetmouse = new Button();
            this.btleftclick = new Button();
            this.btdoubleLeftclick = new Button();
            this.btRightClick = new Button();
            this.btdoublerightClcik = new Button();
            this.checkReset = new CheckBox();
            this.button1 = new Button();
            this.button2 = new Button();
            this.Checkprofile = new CheckBox();
            this.numericSoluongreset = new NumericUpDown();
            this.textBox1 = new TextBox();
            this.label8 = new Label();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.button3 = new Button();
            ((System.ComponentModel.ISupportInitialize)this.gridlist).BeginInit();
            this.numTick.BeginInit();
            this.txtmouseX.BeginInit();
            this.txtmouseY.BeginInit();
            this.numericSoluongreset.BeginInit();
            base.SuspendLayout();
            this.gridlist.Anchor = AnchorStyles.Right | AnchorStyles.Bottom | AnchorStyles.Top;
            //this.gridlist.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridlist.Columns.AddRange(new DataGridViewColumn[] { this.IP, this.Status, this.Action });
            this.gridlist.Location = new System.Drawing.Point(0x14d, -2);
            this.gridlist.Name = "gridlist";
            this.gridlist.Size = new Size(0x165, 0x18e);
            this.gridlist.TabIndex = 0;
            this.IP.DataPropertyName = "IP";
            this.IP.HeaderText = "IP";
            this.IP.Name = "IP";
            this.Status.DataPropertyName = "Status";
            this.Status.HeaderText = "Status";
            this.Status.Name = "Status";
            this.Action.DataPropertyName = "Action";
            this.Action.HeaderText = "Action";
            this.Action.Name = "Action";
            this.btGetPoint.Location = new System.Drawing.Point(0xd5, 0x133);
            this.btGetPoint.Name = "btGetPoint";
            this.btGetPoint.Size = new Size(0x4b, 0x17);
            this.btGetPoint.TabIndex = 1;
            this.btGetPoint.Text = "GetPoint";
            this.btGetPoint.UseVisualStyleBackColor = true;
            this.btGetPoint.Click += new EventHandler(this.btGetPoint_Click);
            this.btSave.Location = new System.Drawing.Point(0xb3, 260);
            this.btSave.Name = "btSave";
            this.btSave.Size = new Size(0x4b, 0x17);
            this.btSave.TabIndex = 1;
            this.btSave.Text = "Save";
            this.btSave.UseVisualStyleBackColor = true;
            this.btSave.Click += new EventHandler(this.btSave_Click_1);
            //this.labpoint.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labpoint.Location = new System.Drawing.Point(0x17d, 0x18f);
            this.labpoint.Name = "labpoint";
            this.labpoint.Size = new Size(0x6d, 0x17);
            this.labpoint.TabIndex = 2;
            this.labpoint.Text = "label1";
            this.labpoint.Visible = false;
            this.txtslapp.Location = new System.Drawing.Point(0x40, 12);
            this.txtslapp.Name = "txtslapp";
            this.txtslapp.Size = new Size(0x1a, 20);
            this.txtslapp.TabIndex = 3;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(1, 15);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x39, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Count App";
            this.txtwidth.Location = new System.Drawing.Point(0x93, 12);
            this.txtwidth.Name = "txtwidth";
            this.txtwidth.Size = new Size(0x1a, 20);
            this.txtwidth.TabIndex = 3;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(0x70, 15);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x23, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Width";
            this.btStart.Location = new System.Drawing.Point(0x62, 0xec);
            this.btStart.Name = "btStart";
            this.btStart.Size = new Size(0x4b, 0x2f);
            this.btStart.TabIndex = 1;
            this.btStart.Text = "Start";
            this.btStart.UseVisualStyleBackColor = true;
            this.btStart.Click += new EventHandler(this.btStart_Click);
            this.timerphut.Interval = 0xea60;
            this.timerphut.Tick += new EventHandler(this.timerphut_Tick);
            this.txt1to24.Location = new System.Drawing.Point(4, 0xa4);
            this.txt1to24.Multiline = true;
            this.txt1to24.Name = "txt1to24";
            this.txt1to24.Size = new Size(0xc6, 0x42);
            this.txt1to24.TabIndex = 5;
            this.txt1to24.Text = "10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10";
            this.timerGiay.Interval = 0x3e8;
            this.timerGiay.Tick += new EventHandler(this.timerGiay_Tick);
            this.timer5p.Interval = 0x493e0;
            this.timer5p.Tick += new EventHandler(this.timer5p_Tick);
            this.timer10p.Interval = 0x927c0;
            this.timer10p.Tick += new EventHandler(this.timer10p_Tick);
            this.btStop.Enabled = false;
            this.btStop.Location = new System.Drawing.Point(0x11, 0xec);
            this.btStop.Name = "btStop";
            this.btStop.Size = new Size(0x4b, 0x2f);
            this.btStop.TabIndex = 1;
            this.btStop.Text = "Stop";
            this.btStop.UseVisualStyleBackColor = true;
            this.btStop.Click += new EventHandler(this.btStop_Click);
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(1, 0x1c);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x19, 13);
            this.label4.TabIndex = 4;
            this.label4.Text = "[F1]";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(0x70, 0x1c);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x19, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "[F2]";
            this.checkBoxStartAndClose.AutoSize = true;
            this.checkBoxStartAndClose.Location = new System.Drawing.Point(4, 0x3f);
            this.checkBoxStartAndClose.Name = "checkBoxStartAndClose";
            this.checkBoxStartAndClose.Size = new Size(0x63, 0x11);
            this.checkBoxStartAndClose.TabIndex = 7;
            this.checkBoxStartAndClose.Text = "Start And Close";
            this.checkBoxStartAndClose.UseVisualStyleBackColor = true;
            this.checkBoxStartAndClose.CheckedChanged += new EventHandler(this.checkBoxStartAndClose_CheckedChanged);
            this.numTick.Enabled = false;
            this.numTick.Location = new System.Drawing.Point(0xeb, 0x3e);
            int[] bits = new int[4];
            ////bits[0] = 0x5f5e100;
            ////this.numTick.Maximum = new decimal(bits);
            this.numTick.Name = "numTick";
            this.numTick.Size = new Size(0x41, 20);
            this.numTick.TabIndex = 8;
            //bits = new int[4];
            //bits[0] = 10;
            //this.numTick.Value = new decimal(bits);
            this.txthight.Location = new System.Drawing.Point(0xf5, 15);
            this.txthight.Name = "txthight";
            this.txthight.Size = new Size(0x1a, 20);
            this.txthight.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(210, 0x1f);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x19, 13);
            this.label3.TabIndex = 4;
            this.label3.Text = "[F3]";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(210, 0x12);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x20, 13);
            this.label6.TabIndex = 4;
            this.label6.Text = "Hight";
            this.checkBoxIsStartApp.AutoSize = true;
            this.checkBoxIsStartApp.Location = new System.Drawing.Point(4, 0x6d);
            this.checkBoxIsStartApp.Name = "checkBoxIsStartApp";
            this.checkBoxIsStartApp.Size = new Size(0x45, 0x11);
            this.checkBoxIsStartApp.TabIndex = 9;
            this.checkBoxIsStartApp.Text = "Start app";
            this.checkBoxIsStartApp.UseVisualStyleBackColor = true;
            this.timerCount.Interval = 0x3e8;
            this.timerCount.Tick += new EventHandler(this.timerCount_Tick);
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(1, 0x13d);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x37, 13);
            this.label7.TabIndex = 10;
            this.label7.Text = "SetMouse";
            this.txtmouseX.Location = new System.Drawing.Point(0x40, 310);
            //bits = new int[4];
            //bits[0] = 0xf423f;
            //this.txtmouseX.Maximum = new decimal(bits);
            this.txtmouseX.Name = "txtmouseX";
            this.txtmouseX.Size = new Size(0x27, 20);
            this.txtmouseX.TabIndex = 11;
            this.txtmouseY.Location = new System.Drawing.Point(0x73, 310);
            //bits = new int[4];
            //bits[0] = 0x98967f;
            //this.txtmouseY.Maximum = new decimal(bits);
            this.txtmouseY.Name = "txtmouseY";
            this.txtmouseY.Size = new Size(0x27, 20);
            this.txtmouseY.TabIndex = 11;
            this.btsetmouse.Location = new System.Drawing.Point(0xa7, 310);
            this.btsetmouse.Name = "btsetmouse";
            this.btsetmouse.Size = new Size(0x2d, 0x17);
            this.btsetmouse.TabIndex = 12;
            this.btsetmouse.Text = "Set";
            this.btsetmouse.UseVisualStyleBackColor = true;
            this.btsetmouse.Click += new EventHandler(this.btsetmouse_Click);
            this.btleftclick.Location = new System.Drawing.Point(13, 0x14d);
            this.btleftclick.Name = "btleftclick";
            this.btleftclick.Size = new Size(0x2d, 0x15);
            this.btleftclick.TabIndex = 12;
            this.btleftclick.Text = "Left";
            this.btleftclick.UseVisualStyleBackColor = true;
            this.btleftclick.Click += new EventHandler(this.btleftclick_Click);
            this.btdoubleLeftclick.Location = new System.Drawing.Point(0x40, 0x14d);
            this.btdoubleLeftclick.Name = "btdoubleLeftclick";
            this.btdoubleLeftclick.Size = new Size(0x2d, 0x15);
            this.btdoubleLeftclick.TabIndex = 12;
            this.btdoubleLeftclick.Text = "dLeft";
            this.btdoubleLeftclick.UseVisualStyleBackColor = true;
            this.btdoubleLeftclick.Click += new EventHandler(this.btdoubleLeftclick_Click);
            this.btRightClick.Location = new System.Drawing.Point(0x74, 0x14d);
            this.btRightClick.Name = "btRightClick";
            this.btRightClick.Size = new Size(0x2d, 0x15);
            this.btRightClick.TabIndex = 12;
            this.btRightClick.Text = "Right";
            this.btRightClick.UseVisualStyleBackColor = true;
            this.btRightClick.Click += new EventHandler(this.btRightClick_Click);
            this.btdoublerightClcik.Location = new System.Drawing.Point(0xa7, 0x14d);
            this.btdoublerightClcik.Name = "btdoublerightClcik";
            this.btdoublerightClcik.Size = new Size(0x2d, 0x15);
            this.btdoublerightClcik.TabIndex = 12;
            this.btdoublerightClcik.Text = "dRight";
            this.btdoublerightClcik.UseVisualStyleBackColor = true;
            this.btdoublerightClcik.Click += new EventHandler(this.btdoublerightClcik_Click);
            this.checkReset.AutoSize = true;
            this.checkReset.Location = new System.Drawing.Point(4, 0x8d);
            this.checkReset.Name = "checkReset";
            this.checkReset.Size = new Size(0x36, 0x11);
            this.checkReset.TabIndex = 13;
            this.checkReset.Text = "Reset";
            this.checkReset.UseVisualStyleBackColor = true;
            this.button1.Location = new System.Drawing.Point(0x102, 0x18f);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 14;
            this.button1.Text = "Send";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.button2.Location = new System.Drawing.Point(0xfc, 0x14d);
            this.button2.Name = "button2";
            this.button2.Size = new Size(0x4b, 0x17);
            this.button2.TabIndex = 15;
            this.button2.Text = "export";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new EventHandler(this.button2_Click);
            this.Checkprofile.AutoSize = true;
            this.Checkprofile.Checked = true;
            this.Checkprofile.CheckState = CheckState.Checked;
            this.Checkprofile.Location = new System.Drawing.Point(0xf5, 0x8d);
            this.Checkprofile.Name = "Checkprofile";
            this.Checkprofile.Size = new Size(0x36, 0x11);
            this.Checkprofile.TabIndex = 0x10;
            this.Checkprofile.Text = "profile";
            this.Checkprofile.UseVisualStyleBackColor = true;
            this.numericSoluongreset.Location = new System.Drawing.Point(0x40, 140);
            this.numericSoluongreset.Name = "numericSoluongreset";
            this.numericSoluongreset.Size = new Size(0x2d, 20);
            this.numericSoluongreset.TabIndex = 0x11;
            //bits = new int[4];
            //bits[0] = 5;
            //this.numericSoluongreset.Value = new decimal(bits);
            this.textBox1.Location = new System.Drawing.Point(15, 0x14d);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0xed, 0x59);
            this.textBox1.TabIndex = 0x12;
            this.textBox1.Text = "Prefs:root=Privacy&path=Advertising";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(0xa4, 0x40);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x43, 13);
            this.label8.TabIndex = 0x13;
            this.label8.Text = "So Lan Click";
            this.timer1.Enabled = true;
            this.timer1.Interval = 0x927c0;
            this.timer1.Tick += new EventHandler(this.timer1_Tick);
            this.button3.Location = new System.Drawing.Point(0xf5, 0xb6);
            this.button3.Name = "button3";
            this.button3.Size = new Size(0x4b, 0x30);
            this.button3.TabIndex = 20;
            this.button3.Text = "RightClick";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new EventHandler(this.button3_Click_1);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            //base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(690, 0x1af);
            base.Controls.Add(this.button3);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.textBox1);
            base.Controls.Add(this.numericSoluongreset);
            base.Controls.Add(this.Checkprofile);
            base.Controls.Add(this.button2);
            base.Controls.Add(this.button1);
            base.Controls.Add(this.checkReset);
            base.Controls.Add(this.btdoublerightClcik);
            base.Controls.Add(this.btRightClick);
            base.Controls.Add(this.btdoubleLeftclick);
            base.Controls.Add(this.btleftclick);
            base.Controls.Add(this.btsetmouse);
            base.Controls.Add(this.txtmouseY);
            base.Controls.Add(this.txtmouseX);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.checkBoxIsStartApp);
            base.Controls.Add(this.numTick);
            base.Controls.Add(this.checkBoxStartAndClose);
            base.Controls.Add(this.txt1to24);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.txthight);
            base.Controls.Add(this.txtwidth);
            base.Controls.Add(this.txtslapp);
            base.Controls.Add(this.labpoint);
            base.Controls.Add(this.btStop);
            base.Controls.Add(this.btStart);
            base.Controls.Add(this.btSave);
            base.Controls.Add(this.btGetPoint);
            base.Controls.Add(this.gridlist);
            base.KeyPreview = true;
            base.Name = "Form1";
            this.Text = "Form1";
            base.MouseMove += new MouseEventHandler(this.Form1_MouseMove);
            base.KeyDown += new KeyEventHandler(this.Form1_KeyDown);
            ((System.ComponentModel.ISupportInitialize)this.gridlist).EndInit();
            this.numTick.EndInit();
            this.txtmouseX.EndInit();
            this.txtmouseY.EndInit();
            this.numericSoluongreset.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion
        private DataGridViewTextBoxColumn Action;
        private Button btdoubleLeftclick;
        private Button btdoublerightClcik;
        private Button btGetPoint;
        private Button btleftclick;
        private Button btRightClick;
        private Button btSave;
        private Button btsetmouse;
        private Button btStart;
        private Button btStop;
        private Button button1;
        private Button button2;
        private Button button3;
        private CheckBox checkBoxIsStartApp;
        private CheckBox checkBoxStartAndClose;
        private CheckBox Checkprofile;
        private CheckBox checkReset;
        //private IContainer components = null;
        private int Count_ClickAuto = 0;
        private DataGridView gridlist;
        private DataGridViewTextBoxColumn IP;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label labpoint;
        private NumericUpDown numericSoluongreset;
        private NumericUpDown numTick;
        
        private DataGridViewTextBoxColumn Status;
        private TextBox textBox1;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Timer timer10p;
        private System.Windows.Forms.Timer timer5p;
        private System.Windows.Forms.Timer timerCount;
        private System.Windows.Forms.Timer timerGiay;
        private System.Windows.Forms.Timer timerphut;
        private TextBox txt1to24;
        private TextBox txthight;
        private NumericUpDown txtmouseX;
        private NumericUpDown txtmouseY;
        private TextBox txtslapp;
        private TextBox txtwidth;
    }
}

